package sdm.time.project6.timeStamps.clocks;

import java.io.* ;

/**
 * Denotes a time instant generated by a clock.
 * Timestamps can be sorted according to their natural order. And can be tested for concurrency.
 * 
 * @author  Sérgio Duarte (smd@di.fct.unl.pt)
 *
 */
public interface TimeStamp extends Comparable<TimeStamp>, Serializable {
	
	boolean concurrent( TimeStamp other ) ;
	
	double value() ;
}